In [3]:
import pandas as pd

# Carga de datasets procesados
df_total = pd.read_csv("../data/processed/total_customers.csv")
df_churn_dist = pd.read_csv("../data/processed/churn_distribution.csv")
df_churn_rate = pd.read_csv("../data/processed/churn_rate_overall.csv")

df_total, df_churn_dist, df_churn_rate

(   total_customers
 0             7043,
    churn  customers
 0  False       5174
 1   True       1869,
    churn_rate_percentage
 0                  26.54)

In [4]:
total_customers = df_total.iloc[0, 0]
total_customers

np.int64(7043)

In [5]:
df_churn_dist

   churn  customers
0  False       5174
1   True       1869

In [6]:
churned_customers = df_churn_dist.loc[
    df_churn_dist["churn"] == True, "customers"
].values[0]

calculated_churn_rate = round(
    100 * churned_customers / total_customers, 2
)

calculated_churn_rate

np.float64(26.54)

In [7]:
df_churn_rate

   churn_rate_percentage
0                  26.54

In [8]:
df_churn_dist["churn_label"] = df_churn_dist["churn"].map({
    True: "Churn",
    False: "No Churn"
})

df_churn_dist

   churn  customers churn_label
0  False       5174    No Churn
1   True       1869       Churn

In [9]:
import pandas as pd

df_total = pd.read_csv("../data/processed/total_customers.csv")
df_churn_dist = pd.read_csv("../data/processed/churn_distribution.csv")
df_churn_rate = pd.read_csv("../data/processed/churn_rate_overall.csv")
df_by_contract = pd.read_csv("../data/processed/churn_by_contract.csv")
df_by_tenure = pd.read_csv("../data/processed/churn_by_tenure_group.csv")
df_by_internet = pd.read_csv("../data/processed/churn_by_internet_service.csv")
df_by_billing = pd.read_csv("../data/processed/churn_by_billing.csv")
df_by_senior = pd.read_csv("../data/processed/churn_by_senior_citizen.csv")
df_summary = pd.read_csv("../data/processed/churn_summary_dashboard.csv")

df_total, df_churn_rate

(   total_customers
 0             7043,
    churn_rate_percentage
 0                  26.54)

In [10]:
def normalize_columns(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("%", "percentage")
    )
    return df

dfs = [
    df_churn_dist,
    df_by_contract,
    df_by_tenure,
    df_by_internet,
    df_by_billing,
    df_by_senior,
    df_summary
]

dfs = [normalize_columns(df) for df in dfs]

df_churn_dist.head()

   churn  customers
0  False       5174
1   True       1869

In [11]:
kpi_overview = pd.DataFrame({
    "total_customers": [df_total.iloc[0, 0]],
    "churn_rate_percentage": [df_churn_rate.iloc[0, 0]]
})

kpi_overview

   total_customers  churn_rate_percentage
0             7043                  26.54

In [12]:
kpi_overview.to_csv(
    "../data/processed/kpi_overview.csv",
    index=False
)

In [13]:
df_churn_dist["churn_label"] = df_churn_dist["churn"].map({
    True: "Churn",
    False: "No Churn"
})

df_churn_dist.to_csv(
    "../data/processed/dashboard_churn_distribution.csv",
    index=False
)

In [14]:
df_by_contract.to_csv(
    "../data/processed/dashboard_churn_by_contract.csv",
    index=False
)

In [15]:
df_by_tenure.to_csv(
    "../data/processed/dashboard_churn_by_tenure.csv",
    index=False
)

In [16]:
df_by_internet.to_csv(
    "../data/processed/dashboard_churn_by_internet.csv",
    index=False
)

In [17]:
df_by_billing.to_csv(
    "../data/processed/dashboard_churn_by_billing.csv",
    index=False
)

In [18]:
df_by_senior["senior_label"] = df_by_senior["senior_citizen"].map({
    1: "Senior",
    0: "No Senior"
})

df_by_senior.to_csv(
    "../data/processed/dashboard_churn_by_senior.csv",
    index=False
)